# Generated by Django 3.2.5 on 2021-07-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20210722_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='', upload_to='static/images/books/2021-07-22'),
            preserve_default=False,
        ),
    ]
