# Generated by Django 3.2.5 on 2021-07-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='famous_quotes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='static/images/books/2021-07-23'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='default_user.png', upload_to='static/images/users/2021-07-23'),
        ),
    ]
