# Generated by Django 3.2.5 on 2021-07-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20210723_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='famous_quotes',
            new_name='quote',
        ),
    ]
