# Generated by Django 3.2.5 on 2021-07-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_auto_20210724_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_add',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
